OCR++/myproject/myapp/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, url
from . import views

urlpatterns = patterns('myproject.myapp.views',
    url(r'^$', 'home', name = 'home')
    url(r'^list/$', 'list', name='list'),
    url(r'^list/runScript/$', 'runScript', name='runScript'),
    # url(r'^list/vote/$', 'vote', name='vote'),
    # url(r'^list/upload/$', 'upload', name='upload'),
)

OCR++/myproject/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView
from myapp import views

urlpatterns = patterns('',
	# (r'^myapp/', include('myproject.myapp.urls')),
    url(r'^author_names/$', views.author_names, name = 'author_names'),
	url(r'^getauthor/$', views.getauthor, name = 'getauthor'),
	url(r'^gettitle/$', views.gettitle, name = 'gettitle'),
	url(r'^title/$', views.title, name = 'title'),
	url(r'^home/$', views.home, name = 'home'),
    url(r'^team/$', views.team, name = 'team'),
	# url(r'^$', views.home, name = 'home'),
	url(r'^list/$', views.list, name = 'list'),
	url(r'^email/$', views.email, name = 'email'),
	url(r'^getemail/$', views.getemail, name = 'getemail'),
	url(r'^list/$', views.list, name = 'list'),
    url(r'^affiliation/$', views.affiliation, name = 'affiliation'),
	url(r'^getaffiliation/$', views.getaffiliation, name = 'getaffiliation'),
	# url(r'^citation/$', views.citation, name = 'citation'),
    # url(r'^reference/$', views.reference, name = 'reference'),
    url(r'^map/$', views.map, name = 'map'),
	url(r'^getmap/$', views.getmap, name = 'getmap'),
    url(r'^url/$', views.url, name = 'url'),
	url(r'^geturl/$', views.geturl, name = 'geturl'),
    url(r'^footnote/$', views.footnote, name = 'footnote'),
	url(r'^getfootnote/$', views.getfootnote, name = 'getfootnote'),
    url(r'^section/$', views.section, name = 'section'),
	url(r'^getsection/$', views.getsection, name = 'getsection'),
    url(r'^table_heading/$', views.table_heading, name = 'table_heading'),
    url(r'^figure_heading/$', views.figure_heading, name = 'figure_heading'),
	url(r'^gettabfig/$', views.gettabfig, name = 'gettabfig'),
    url(r'^citref/$', views.citref, name = 'citref'),
    url(r'^getcitref/$', views.getcitref, name = 'getcitref'),
    url(r'^getref_feature/$', views.getref_feature, name = 'getref_feature'),
    url(r'^ref_feature/$', views.ref_feature, name = 'ref_feature'),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

OCR++/myproject/myapp/models.py
# -*- coding: utf-8 -*-
from django.db import models

class Document(models.Model):
    docfile = models.FileField(upload_to='documents/')

class UserDetails(models.Model):
	"""docstring for rPapers"""
	paperid = models.FloatField()
	userid = models.CharField(max_length= 100)
	user_email = models.EmailField()
	def __str__(self):
		return self.paperid

class Response(models.Model):
	"""docstring for response"""
	# userdetails = models.ForeignKey(UserDetails)
	# paperid = models.IntegerField()
	user_email = models.EmailField()
	title = models.FloatField()
	authorNames = models.FloatField()
	urls = models.FloatField()
	email = models.FloatField()
	affiliation = models.FloatField()
	# references = models.FloatField()
	sections = models.FloatField()
	emailAuthMap = models.FloatField()
	figHeading = models.FloatField()
	Footnotes = models.FloatField()
	TableHeading = models.FloatField()
	# citToRef = models.FloatField()

	def __str__(self):
		return self.title

OCR++/myproject/myapp/forms.py
# -*- coding: utf-8 -*-
from django import forms

class DocumentForm(forms.Form):
    docfile = forms.FileField(
        label='Select a file'
    )

OCR++/myproject/myapp/views.py
# -*- coding: utf-8 -*-
from __future__ import division
from django.shortcuts import render, redirect
from django.shortcuts import render_to_response
from django.shortcuts import get_object_or_404
from django.template import RequestContext
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
import glob
from myproject.myapp.models import Document
from myproject.myapp.models import Response, UserDetails
from myproject.myapp.forms import DocumentForm
import subprocess
from subprocess import Popen, PIPE
import os.path

script_dir = "/var/www/html/OCR++/myproject/myapp/"
directory = "/var/www/html/OCR++/myproject/media/documents/";

def runScript():
    # print "ayaya"
    subprocess.call("rm " + directory + "input.pdf", shell=True)
    subprocess.call(directory + "Clean.sh",shell=True)
    # print "runn"
    # print paperid
    file_name = glob.glob(directory+'*.pdf')
    # print file_name
    srno = 1
    fname = file_name[0]
    fn = fname.split('/')
    fn = fn[-1]
    # print "Views.py : "+fn
    # subprocess.call("clear", shell=True)
    subprocess.call("mv " + directory + fn + " " + directory + "input.pdf", shell=True)
    subprocess.call("rm -r " + directory + "eval_*.txt", shell=True)
    subprocess.call("rm -r /var/www/html/media/documents/*",shell=True)
    subprocess.call("cp " + directory + "input.pdf /var/www/html/media/documents/", shell=True)
    subprocess.call("cp -r " + directory + "paper/* /var/www/html/media/documents/", shell=True)
    subprocess.call("cp -r " + directory + "eval* /var/www/html/media/documents/",shell=True)
    subprocess.call("cp -r " + directory + "output.xml /var/www/html/media/documents/",shell=True)
    # subprocess.call("python " + directory + "main_script_batch.py", shell=True)
    subprocess.call(directory + "ShellScript.sh",shell=True)
    return HttpResponse("Done")

def list(request):
    if request.method == 'GET':
        return HttpResponseRedirect("/home/")
        # return HttpResponse('This page shows a list of most recent posts.')
        # pass
    # Handle file upload
    if request.method == 'POST':
        form = DocumentForm(request.POST, request.FILES)
        if form.is_valid():
            newdoc = Document(docfile = request.FILES['docfile'])
            newdoc.save()
            runScript()

            # Redirect to the document list after POST
            return HttpResponseRedirect("../home/")
    else:
        form = DocumentForm() # A empty, unbound form

    # Load documents for the list page
    documents = Document.objects.all()

    # Render list page with the documents and the form
    return render_to_response(
        'home.html',
        {'documents': documents, 'form': form},

        context_instance=RequestContext(request)
    )

def author_names(request):
    return render(request, "author_names.html")

def title(request):
    return render(request, "title.html")

def home(request):
    return render(request, "home.html", {"paper_name" : "../../media/documents/input.pdf"})

def email(request):
    return render(request, "email.html")

def affiliation(request):
    return render(request, "affiliation.html")

def map(request):
    return render(request, "map.html")

def section(request):
    return render(request, "section.html")

def table_heading(request):
    return render(request, "table_heading.html")

def figure_heading(request):
    return render(request, "figure_heading.html")

def url(request):
    return render(request, "url.html")

def footnote(request):
    return render(request, "footnote.html")

def citref(request):
    return render(request, "citref.html")

def ref_feature(request):
    return render(request, "reference.html")

def team(request):
    return render(request, "team.html")

def getauthor(request):
    if request.method == 'GET':
        resp = ""
        if os.path.isfile(directory + "eval_author.txt"):
            resp = open(directory + "eval_author.txt").read()
            if len(resp)==0:
                resp = "No file"
        else:
            resp = "No file"

        response = {'status': 1, 'message': "Confirmed!!", 'url':'/author_names/'}
        return HttpResponse(resp, content_type='string')

def gettitle(request):
    if request.method == 'GET':
        resp = ""
        if os.path.isfile(directory + "eval_title.txt"):
            resp = open(directory + "eval_title.txt").read()
            if len(resp)==0:
                resp = "No file"
        else:
            resp = "No file"

        response = {'status': 1, 'message': "Confirmed!!", 'url':'/title/'}
        return HttpResponse(resp, content_type='string')

def getemail(request):
    if request.method == 'GET':
        resp = ""
        if os.path.isfile(directory + "eval_emails.txt"):
            resp = open(directory + "eval_emails.txt").read()
            if len(resp)==0:
                resp = "No file"
        else:
            resp = "No file"

        response = {'status': 1, 'message': "Confirmed!!", 'url':'/email/'}
        return HttpResponse(resp, content_type='string')

def getaffiliation(request):
    if request.method == 'GET':
        resp = ""
        if os.path.isfile(directory + "eval_Affiliations.txt"):
            resp = open(directory + "eval_Affiliations.txt").read()
            if len(resp)==0:
                resp = "No file"
        else:
            resp = "No file"

        response = {'status': 1, 'message': "Confirmed!!", 'url':'/affiliation/'}
        return HttpResponse(resp, content_type='string')

def getmap(request):
    if request.method == 'GET':
        resp = ""
        if os.path.isfile(directory + "eval_map.txt"):
            resp = open(directory + "eval_map.txt").read()
            if len(resp)==0:
                resp = "No file"
        else:
            resp = "No file"

        response = {'status': 1, 'message': "Confirmed!!", 'url':'/map/'}
        return HttpResponse(resp, content_type='string')

def getsection(request):
    if request.method == 'GET':
        resp = ""
        if os.path.isfile(directory + "eval_Secmap.txt"):
            resp = open(directory + "eval_Secmap.txt").read()
            if len(resp)==0:
                resp = "No file"
        else:
            resp = "No file"

        response = {'status': 1, 'message': "Confirmed!!", 'url':'/section/'}
        return HttpResponse(resp, content_type='string')

def gettabfig(request):
    if request.method == 'GET':
        resp = ""
        if os.path.isfile(directory + "eval_tables_figures.txt"):
            resp = open(directory + "eval_tables_figures.txt").read()
            if len(resp)==0:
                resp = "No file"
        else:
            resp = "No file"

        response = {'status': 1, 'message': "Confirmed!!", 'url':'/table_heading/'}
        return HttpResponse(resp, content_type='string')

def geturl(request):
    if request.method == 'GET':
        resp = ""
        if os.path.isfile(directory + "eval_url.txt"):
            resp = open(directory + "eval_url.txt").read()
            if len(resp)==0:
                resp = "No file"
        else:
            resp = "No file"

        response = {'status': 1, 'message': "Confirmed!!", 'url':'/url/'}
        return HttpResponse(resp, content_type='string')

def getfootnote(request):
    if request.method == 'GET':
        resp = ""
        if os.path.isfile(directory + "eval_footnote.txt"):
            resp = open(directory + "eval_footnote.txt").read()
            if len(resp)==0:
                resp = "No file"
        else:
            resp = "No file"

        response = {'status': 1, 'message': "Confirmed!!", 'url':'/footnote/'}
        return HttpResponse(resp, content_type='string')

def getcitref(request):
    if request.method == 'GET':
        resp = ""
        # print os.path.isfile(directory + "eval_cit2ref.xml")
        if os.path.isfile(directory + "eval_cit2ref.txt"):
            # print "aya toh****************"
            resp = open(directory + "eval_cit2ref.txt").read()
            if len(resp)==0:
                resp = "No file"
        else:
            resp = "No file"

        response = {'status': 1, 'message': "Confirmed!!", 'url':'/citref/'}
        return HttpResponse(resp, content_type='string')

def getref_feature(request):
    # if request.method == 'GET':
    #     resp = ""
    #     if os.path.isfile(directory + "testResults/xmls/input.xml"):
    #         resp = open(directory + "testResults/xmls/input.xml").read()
    #         if len(resp)==0:
    #             resp = "No file"
    #     else:
    #         resp = "No file"

    #     response = {'status': 1, 'message': "Confirmed!!", 'url':'/ref_feature/'}
    #     return HttpResponse(resp, content_type='string')
    if request.method == 'GET':
        resp = ""
        if os.path.isfile(directory + "eval_ref.txt"):
            # print "aya toh****************"
            resp = open(directory + "eval_ref.txt").read()
            if len(resp)==0:
                resp = "No file"
        else:
            resp = "No file"

        response = {'status': 1, 'message': "Confirmed!!", 'url':'/ref_feature/'}
        return HttpResponse(resp, content_type='string')

OCR++/myproject/myapp/templates/backup_home.html
<!DOCTYPE html>
<html lang="en">
<META HTTP-EQUIV="refresh" CONTENT="1000000">
<head>
	{% include "includes/header.html" %}

	<style>
        * {
            padding: 0;
            margin: 0;
        }
        /*body {
            margin: 100px auto;
            font-family: arial;
            font-size: 100%;
            text-align: center;
        }*/
        #searchbar input[type="text"] {
            margin: 0 auto;
            text-align: center;
            width: 430px;
            display: block;
            padding: 20px;
            font-size: 1.2em;
            border: solid 2px #333;
            -webkit-border-radius: 4px;
               -moz-border-radius: 4px;
                    border-radius: 4px;
        }
		#searchbar {
			margin: 20px auto;
            font-family: arial;
            font-size: 100%;
            text-align: center;
		}
        #searchbar ul{
            list-style: none;
            display: inline-block;
            margin-top: 10px;
            width: 480px;
            text-align: left;
        }
        #searchbar ul li {
            display: block;
            position: relative;
            margin: 2px auto;
            padding: 20px;
            border: solid 2px #fff;
            background: #f1f1f1;
            font-size: 0.9em;
            color: #333;
            -webkit-border-radius: 4px;
               -moz-border-radius: 4px;
                    border-radius: 4px;
            -webkit-transition: 0.3s;
               -moz-transition: 0.3s;
                    transition: 0.3s;
        }
        #searchbar ul li a {
            position: absolute;
            left: 120px;
            color: #999;
        }

        #searchbar ul li:hover, .focused {
            background: #333;
            color: #fff;

        }

    </style>
    <!-- <script src="http://fb.me/react-0.10.0.js"></script>
    <script src="http://fb.me/JSXTransformer-0.10.0.js"></script> -->
</head>


<body class="nav-md">

	<div class="container body">


		<div class="main_container">

			{% include "includes/leftandtop.html" %}
			<!-- <script>
			$.ajax({
				url: '../userdetails/',
				type: 'GET',
				success: function(response) {
					console.log(response['name'])
					document.getElementById('name').innerHTML = response['name']
					document.getElementById('name1').innerHTML = response['name'].split()[0]
					document.getElementById('name2').innerHTML = response['name']
				},
				error: function(error) {
					console.log(error);
				},

			});
			</script> -->
			<!-- page content -->
			<div class="right_col" role="main">

				<div class="row">
					<div class="col-md-12 col-sm-12 col-xs-12">
						<div class="dashboard_graph">

							<div class="row x_title">
								<div class="col-md-6">
									<h3>Upload file</h3>
								</div>
							</div>

							<div id="header">
								<form action="../list/" method="post" enctype="multipart/form-data">
									{% csrf_token %}
									{{ form.non_field_errors }}
									{{ form.docfile.label_tag }} {{ form.docfile.help_text }}
									{{ form.docfile.errors }}
									{{ form.docfile }}
									<label for="id_docfile">Select a file:</label>

									<input id="id_docfile" name="docfile" type="file">
									<br>
									<p><input id="submit" type="submit" value="Upload" /></p>
								</form>

								<!-- <form action="../list/" method="post" enctype="multipart/form-data">
									<input name="csrfmiddlewaretoken" value="9onHPt3K6XHWcLShYSAQK3Wxb4Q6QUNz" type="hidden">

									<label for="id_docfile">Select a file:</label>

									<input id="id_docfile" name="docfile" type="file">
									<br>
									<button id="submit" class="btn btn-success btn-sm" type="submit">Upload</button>
								</form> -->
							</div>



							<div class="clearfix"></div>
						</div>


					</div>

				</div>
				<br />
				<div class = "row">
					<div class="col-md-12 col-sm-12 col-xs-12">
				        <embed class = "x_panel" src={{paper_name}} height="500px">
					</div>
				</div>
				<!-- footer content -->
				<footer>
					{% include "includes/footer.html" %}
				</footer>
				<!-- /footer content -->
			</div>

		</div>

	</div>

	<div id="custom_notifications" class="custom-notifications dsp_none">
		<ul class="list-unstyled notifications clearfix" data-tabbed_notifications="notif-group">
		</ul>
		<div class="clearfix"></div>
		<div id="notif-group" class="tabbed_notifications"></div>
	</div>

	<script src="/static/js/bootstrap.min.js"></script>

	<!-- gauge js --><!-- 
	 <script type="text/javascript" src="/static/js/gauge/gauge.min.js"></script>
	<script type="text/javascript" src="/static/js/gauge/gauge_demo.js"></script> --> 
	<!-- chart js --><!-- 
	<script src="/static/js/chart/static/js/chart.min.js"></script> -->
	<!-- bootstrap progress js -->
	<script src="/static/js/progressbar/bootstrap-progressbar.min.js"></script>
	<script src="/static/js/nicescroll/jquery.nicescroll.min.js"></script>
	<!-- icheck -->
	<!-- <script src="/static/js/icheck/icheck.min.js"></script> -->
	<!-- daterangepicker -->
	<!-- <script type="text/javascript" src="/static/js/moment.min.js"></script>
	<script type="text/javascript" src="/static/js/datepicker/daterangepicker.js"></script> -->

	<script src="/static/js/custom.js"></script>

	<!-- flot js -->
	<!--[if lte IE 8]><script type="text/javascript" src="/static/js/excanvas.min.js"></script><![endif]-->
	<!-- 
	<script type="text/javascript" src="/static/js/flot/jquery.flot.js"></script>
	<script type="text/javascript" src="/static/js/flot/jquery.flot.pie.js"></script>
	<script type="text/javascript" src="/static/js/flot/jquery.flot.orderBars.js"></script>
	<script type="text/javascript" src="/static/js/flot/jquery.flot.time.min.js"></script>
	<script type="text/javascript" src="/static/js/flot/date.js"></script>
	<script type="text/javascript" src="/static/js/flot/jquery.flot.spline.js"></script>
	<script type="text/javascript" src="/static/js/flot/jquery.flot.stack.js"></script>
	<script type="text/javascript" src="/static/js/flot/curvedLines.js"></script>
	<script type="text/javascript" src="/static/js/flot/jquery.flot.resize.js"></script> -->


	<!-- worldmap --><!-- 
	<script type="text/javascript" src="/static/js/maps/jquery-jvectormap-2.0.3.min.js"></script>
	<script type="text/javascript" src="/static/js/maps/gdp-data.js"></script>
	<script type="text/javascript" src="/static/js/maps/jquery-jvectormap-world-mill-en.js"></script>
	<script type="text/javascript" src="/static/js/maps/jquery-jvectormap-us-aea-en.js"></script> -->
	<!-- pace -->
	 <!-- <script src="/static/js/pace/pace.min.js"></script> -->

	<!-- skycons -->
	<script src="/static/js/skycons/skycons.min.js"></script>
	<!-- <script>
		var icons = new Skycons({
			"color": "#73879C"
		}),
		list = [
			"clear-day", "clear-night", "partly-cloudy-day",
			"partly-cloudy-night", "cloudy", "rain", "sleet", "snow", "wind",
			"fog"
		],
		i;

		for (i = list.length; i--;)
		icons.set(list[i], list[i]);

		icons.play();
	</script> -->

										<!-- dashbord linegraph -->
	<!-- <script>
		var doughnutData = [
			{
				value: 30,
				color: "#455C73"
			},
			{
				value: 30,
				color: "#9B59B6"
			},
			{
				value: 60,
				color: "#BDC3C7"
			},
			{
				value: 100,
				color: "#26B99A"
			},
			{
				value: 120,
				color: "#3498DB"
			}
		];
		var myDoughnut = new Chart(document.getElementById("canvas1").getContext("2d")).Doughnut(doughnutData);
	</script> -->
<!-- /dashbord linegraph -->
<!-- datepicker -->

	<script>
		// NProgress.done();
	</script>
<!-- /datepicker -->
<!-- /footer content -->
</body>

</html>

OCR++/myproject/myapp/templates/home.html
<!DOCTYPE html>
<html lang="en">

<head>
	{% include "includes/header.html" %}

	<style>
        * {
            padding: 0;
            margin: 0;
        }
        /*body {
            margin: 100px auto;
            font-family: arial;
            font-size: 100%;
            text-align: center;
        }*/
        #searchbar input[type="text"] {
            margin: 0 auto;
            text-align: center;
            width: 430px;
            display: block;
            padding: 20px;
            font-size: 1.2em;
            border: solid 2px #333;
            -webkit-border-radius: 4px;
               -moz-border-radius: 4px;
                    border-radius: 4px;
        }
		#searchbar {
			margin: 20px auto;
            font-family: arial;
            font-size: 100%;
            text-align: center;
		}
        #searchbar ul{
            list-style: none;
            display: inline-block;
            margin-top: 10px;
            width: 480px;
            text-align: left;
        }
        #searchbar ul li {
            display: block;
            position: relative;
            margin: 2px auto;
            padding: 20px;
            border: solid 2px #fff;
            background: #f1f1f1;
            font-size: 0.9em;
            color: #333;
            -webkit-border-radius: 4px;
               -moz-border-radius: 4px;
                    border-radius: 4px;
            -webkit-transition: 0.3s;
               -moz-transition: 0.3s;
                    transition: 0.3s;
        }
        #searchbar ul li a {
            position: absolute;
            left: 120px;
            color: #999;
        }

        #searchbar ul li:hover, .focused {
            background: #333;
            color: #fff;

        }

    </style>
    <!-- <script src="http://fb.me/react-0.10.0.js"></script>
    <script src="http://fb.me/JSXTransformer-0.10.0.js"></script> -->
</head>


<body class="nav-md">

	<div class="container body">


		<div class="main_container">

			{% include "includes/leftandtop.html" %}
			<!-- <script>
			$.ajax({
				url: '../userdetails/',
				type: 'GET',
				success: function(response) {
					console.log(response['name'])
					document.getElementById('name').innerHTML = response['name']
					document.getElementById('name1').innerHTML = response['name'].split()[0]
					document.getElementById('name2').innerHTML = response['name']
				},
				error: function(error) {
					console.log(error);
				},

			});
			</script> -->
			<!-- page content -->
			<div class="right_col" role="main">

				<div class="row">
					<div class="col-md-12 col-sm-12 col-xs-12">
						<div class="dashboard_graph">

							<div class="row x_title">
								<div class="col-md-6">
									<h3>Upload file</h3>
								</div>
							</div>

							<div id="header">
								<form action="../list/" method="post" enctype="multipart/form-data">
									{% csrf_token %}
									{{ form.non_field_errors }}
									{{ form.docfile.label_tag }} {{ form.docfile.help_text }}
									{{ form.docfile.errors }}
									{{ form.docfile }}
									<label for="id_docfile">Select a file:</label>

									<input id="id_docfile" name="docfile" type="file">
									<br>
									<p><input id="submit" type="submit" value="Upload" /></p>
								</form>

								<!-- <form action="../list/" method="post" enctype="multipart/form-data">
									<input name="csrfmiddlewaretoken" value="9onHPt3K6XHWcLShYSAQK3Wxb4Q6QUNz" type="hidden">

									<label for="id_docfile">Select a file:</label>

									<input id="id_docfile" name="docfile" type="file">
									<br>
									<button id="submit" class="btn btn-success btn-sm" type="submit">Upload</button>
								</form> -->
							</div>



							<div class="clearfix"></div>
						</div>


					</div>

				</div>
				<br />
				<div class = "row">
					<div class="col-md-12 col-sm-12 col-xs-12">
				        <embed class = "x_panel" src={{paper_name}} height="500px">
					</div>
				</div>
				<!-- footer content -->
				<footer>
					{% include "includes/footer.html" %}
				</footer>
				<!-- /footer content -->
			</div>

		</div>

	</div>

	<div id="custom_notifications" class="custom-notifications dsp_none">
		<ul class="list-unstyled notifications clearfix" data-tabbed_notifications="notif-group">
		</ul>
		<div class="clearfix"></div>
		<div id="notif-group" class="tabbed_notifications"></div>
	</div>

	<script src="/static/js/bootstrap.min.js"></script>

	<!-- gauge js --><!-- 
	 <script type="text/javascript" src="/static/js/gauge/gauge.min.js"></script>
	<script type="text/javascript" src="/static/js/gauge/gauge_demo.js"></script> --> 
	<!-- chart js --><!-- 
	<script src="/static/js/chart/static/js/chart.min.js"></script> -->
	<!-- bootstrap progress js -->
	<script src="/static/js/progressbar/bootstrap-progressbar.min.js"></script>
	<script src="/static/js/nicescroll/jquery.nicescroll.min.js"></script>
	<!-- icheck -->
	<!-- <script src="/static/js/icheck/icheck.min.js"></script> -->
	<!-- daterangepicker -->
	<!-- <script type="text/javascript" src="/static/js/moment.min.js"></script>
	<script type="text/javascript" src="/static/js/datepicker/daterangepicker.js"></script> -->

	<script src="/static/js/custom.js"></script>

	<!-- flot js -->
	<!--[if lte IE 8]><script type="text/javascript" src="/static/js/excanvas.min.js"></script><![endif]-->
	<!-- 
	<script type="text/javascript" src="/static/js/flot/jquery.flot.js"></script>
	<script type="text/javascript" src="/static/js/flot/jquery.flot.pie.js"></script>
	<script type="text/javascript" src="/static/js/flot/jquery.flot.orderBars.js"></script>
	<script type="text/javascript" src="/static/js/flot/jquery.flot.time.min.js"></script>
	<script type="text/javascript" src="/static/js/flot/date.js"></script>
	<script type="text/javascript" src="/static/js/flot/jquery.flot.spline.js"></script>
	<script type="text/javascript" src="/static/js/flot/jquery.flot.stack.js"></script>
	<script type="text/javascript" src="/static/js/flot/curvedLines.js"></script>
	<script type="text/javascript" src="/static/js/flot/jquery.flot.resize.js"></script> -->


	<!-- worldmap --><!-- 
	<script type="text/javascript" src="/static/js/maps/jquery-jvectormap-2.0.3.min.js"></script>
	<script type="text/javascript" src="/static/js/maps/gdp-data.js"></script>
	<script type="text/javascript" src="/static/js/maps/jquery-jvectormap-world-mill-en.js"></script>
	<script type="text/javascript" src="/static/js/maps/jquery-jvectormap-us-aea-en.js"></script> -->
	<!-- pace -->
	 <!-- <script src="/static/js/pace/pace.min.js"></script> -->

	<!-- skycons -->
	<script src="/static/js/skycons/skycons.min.js"></script>
	<!-- <script>
		var icons = new Skycons({
			"color": "#73879C"
		}),
		list = [
			"clear-day", "clear-night", "partly-cloudy-day",
			"partly-cloudy-night", "cloudy", "rain", "sleet", "snow", "wind",
			"fog"
		],
		i;

		for (i = list.length; i--;)
		icons.set(list[i], list[i]);

		icons.play();
	</script> -->

										<!-- dashbord linegraph -->
	<!-- <script>
		var doughnutData = [
			{
				value: 30,
				color: "#455C73"
			},
			{
				value: 30,
				color: "#9B59B6"
			},
			{
				value: 60,
				color: "#BDC3C7"
			},
			{
				value: 100,
				color: "#26B99A"
			},
			{
				value: 120,
				color: "#3498DB"
			}
		];
		var myDoughnut = new Chart(document.getElementById("canvas1").getContext("2d")).Doughnut(doughnutData);
	</script> -->
<!-- /dashbord linegraph -->
<!-- datepicker -->

	<script>
		// NProgress.done();
	</script>
<!-- /datepicker -->
<!-- /footer content -->
</body>

</html>